# Generated by Django 3.1.5 on 2021-07-23 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_update', models.BooleanField(default=False)),
                ('customer_contacted', models.BooleanField(default=False)),
                ('customer_contact_updated', models.BooleanField(default=False)),
                ('customer_contected_time', models.DateTimeField(auto_now=True)),
                ('file_picked', models.BooleanField(default=False)),
                ('file_picked_updated', models.BooleanField(default=False)),
                ('file_picked_time', models.DateTimeField(auto_now=True)),
                ('remark_message', models.CharField(blank=True, max_length=100, null=True)),
                ('remark_message_updated', models.BooleanField(default=False)),
                ('remark_message_updated_at', models.DateTimeField(auto_now=True)),
                ('file_pickup_process_completed', models.BooleanField(default=False)),
                ('file_pickup_process_completed_at', models.DateTimeField(auto_now=True)),
                ('payout', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_updated', models.BooleanField(default=False)),
                ('payout_updated_at', models.DateTimeField(auto_now=True)),
                ('actual_disbursement', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_recieved_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_recieved_date', models.DateTimeField(blank=True, null=True)),
                ('payout_recieved', models.CharField(blank=True, max_length=100, null=True)),
                ('incentives', models.CharField(blank=True, max_length=100, null=True)),
                ('net_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('incentives_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('other_details_updated', models.BooleanField(default=False)),
                ('verification_pending', models.BooleanField(default=False)),
                ('verification_approved', models.BooleanField(default=False)),
                ('verification_rejected', models.BooleanField(default=False)),
                ('verification_rejection_reason', models.TextField(blank=True, null=True)),
                ('verification_approved_at', models.DateTimeField(auto_now=True, null=True)),
                ('verification_rejected_at', models.DateTimeField(auto_now=True, null=True)),
                ('verification_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_approve', to=settings.AUTH_USER_MODEL)),
                ('verification_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_reject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_user', models.CharField(blank=True, max_length=100, null=True)),
                ('read_chat_notification', models.BooleanField(default=False)),
                ('read_lead_notification', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_lead', to='webapp.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
