# Generated by Django 3.2.7 on 2021-10-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gst_proof_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='housing_loan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_gst',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mortgage_loan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='personal_loan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vehical_loan',
        ),
    ]
