# Generated by Django 3.2.7 on 2021-10-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211004_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='legal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='other',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='other',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='taxation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='taxation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tradmark',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tradmark',
            name='updated',
        ),
    ]
