# Generated by Django 3.2.7 on 2021-10-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20211004_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='actual_disbursement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='other_details_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='payout_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='payout_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
